### ISSUE TITLE
function "api_call" in api.c cause stack corruption

### ISSUE THREAD

**Issue by rickerliang** [djberg96/win32-api#12]
"return_value = ptr->function(param)" in api_call function will cause stack corruption.
This statement cause the compiler generate assembly like this:
 
sub         esp,50h  
mov        ecx,14h  
lea          esi,[ebp-58h]  
mov        edi,esp  
rep movs    dword ptr es:[edi],dword ptr [esi]  
call          windows_api 

The calling convention of window api is __stdcall, callee pops its own arguments from the stack, so windows api's return statement usually like this (assembly) ret xxh, xxh == arguments count * 4 byte.
Argument counts are vary from api to api, not all windows api uses 20 arguments (and ret 50h) especially some api has no argument, in that situation, before and after api call, esp register can not keep the same value, stack corruption occur.
Pass the argument according to api's prototype could fix this problem.

**Comment by djberg96** [comment]
I generally encourage people to use FFI over win32-api. If you have a patch that passes the test suite, then I'll accept it.

**Comment by rickerliang** [comment]
Got it

**Comment by djberg96** [comment]
Merged your patch. :)
