### ISSUE TITLE
Ruby 2.2 support precompiled binaries

### ISSUE THREAD

**Issue by Annih** [djberg96/win32-api#14]
Hi,

Now that ruby 2.2 has an official installer, could it be possible to publish a new version on ruby gems ?

Thanks!

**Comment by djberg96** [comment]
I suppose I could. I'm always surprised to see that people are still using this. I never use it any longer. I don't suppose you would be interested in taking over maintenance, would you?

**Comment by djberg96** [comment]
BTW, I'll check but I think I may have to wait until the next point release because of this bug:

https://bugs.ruby-lang.org/issues/10941

**Comment by djberg96** [comment]
Gave it a shot and it worked. I pushed out 1.5.3 this evening.

**Comment by Annih** [comment]
Thanks @djberg96  it works perfectly :)

**Comment by matkoniecz** [comment]
> I suppose I could. I'm always surprised to see that people are still using this. I never use it any longer. 

What you recommend? From quick looking over your project it seems that your choice is https://github.com/ffi/ffi - is it correct? 

And to answer why I wanted to use this library - found [code](http://stackoverflow.com/questions/14220386/ruby-win32-api-getfocus-and-getwindowtext) that is solving my problem - and this code is using it.

**Comment by cosmo0920** [comment]
ffi migration is not active now.
If you interested in migrating `ffi` based gem, please look at `ffi` branch.
But I don't want to migrate ffi based gem right now because Windows version of Fluentd depends on this gem and Fluentd does not support JRuby.
