### ISSUE TITLE
Can't call GetModuleFileName on mswin64

### ISSUE THREAD

**Issue by nurse** [djberg96/win32-api#15]
> % ruby -rwin32/api -e"a=Win32::API.new('GetModuleFileName','LPL','L');p a.call(0,str='.'*256,256)"
> 0

It is expected to store `a` the path of ruby binary and output the size of it.

https://msdn.microsoft.com/ja-jp/library/windows/desktop/ms683197%28v=vs.85%29.aspx

**Comment by phasis68** [comment]
What is your ruby version and win32-api version?

Works fine for me with ruby 2.2.2 and win32-api 1.5.3 on Windows 7

> C:\>ruby -rwin32/api -ve"a=Win32::API.new('GetModuleFileName','LPL','L');p a.call(0,str='.'*256,256)"
> ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mswin64_120]
> 19

**Comment by nurse** [comment]
Thanks, my environment is ruby 2.3.0dev (2015-05-30 trunk 50685) [x64-mswin64_120].
And I confirmed it works on ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32].

I'll investigate my environment...

**Comment by djberg96** [comment]
We don't ship a binary for 2.3 yet. You will have to build from source to use 2.3 right now.

**Comment by nurse** [comment]
It is because the gem version is 1.4.8, which is the last version of distributed gem including source.
I built binary from GitHub source.
